# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sample-extension"
client_id = "97e447fb78927c85ab3e541cd6125894"
application_url = "https://warner-injury-pj-avenue.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes,read_products,write_products"

[auth]
redirect_urls = [
  "https://warner-injury-pj-avenue.trycloudflare.com/auth/callback",
  "https://warner-injury-pj-avenue.trycloudflare.com/auth/shopify/callback",
  "https://warner-injury-pj-avenue.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "steppingedge-theme-prototype-1.myshopify.com"
